-- 000001_initial_schema.up.sql
--
-- Initial schema for the notification system. Creates four tables in FK
-- order (batches, templates, notifications, notification_logs), the
-- updated_at trigger function, and every required index per CLAUDE.md §11.
--
-- IDs are UUID v7 generated by the application (ADR-0002 / CLAUDE.md §11);
-- this file does not enable pgcrypto / uuid-ossp because the database never
-- needs to generate one itself.

BEGIN;

-- --- updated_at auto-update trigger function -----------------------------
-- Reused by every table that has updated_at. Sets the column to NOW() on
-- every UPDATE so application code does not have to remember.

CREATE OR REPLACE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- --- batches -------------------------------------------------------------
-- A group of 1..1000 notifications created in one API call. No status of
-- its own — aggregate counts are derived on the fly.

CREATE TABLE batches (
    id              UUID PRIMARY KEY,
    correlation_id  TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_batches_correlation_id ON batches (correlation_id);

-- --- templates -----------------------------------------------------------
-- Reusable message bodies with {{.Variable}} placeholders. Channel-scoped
-- because a template authored for SMS has different length / formatting
-- constraints than one authored for email.

CREATE TABLE templates (
    id          UUID PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    channel     TEXT NOT NULL,
    body        TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT templates_channel_check
        CHECK (channel IN ('sms', 'email', 'push'))
);

CREATE TRIGGER set_updated_at_templates
    BEFORE UPDATE ON templates
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();

-- --- notifications -------------------------------------------------------
-- The central entity. Status drives the lifecycle FSM (see domain/status.go);
-- check constraints enforce the legal value set at the database boundary
-- as belt-and-braces alongside the application-level validation.

CREATE TABLE notifications (
    id              UUID PRIMARY KEY,
    batch_id        UUID REFERENCES batches(id) ON DELETE SET NULL,
    idempotency_key TEXT,
    correlation_id  TEXT NOT NULL,

    channel   TEXT NOT NULL,
    priority  TEXT NOT NULL,
    recipient TEXT NOT NULL,
    content   TEXT NOT NULL,

    status        TEXT NOT NULL,
    attempts      INTEGER NOT NULL DEFAULT 0,
    last_error    TEXT NOT NULL DEFAULT '',
    next_retry_at TIMESTAMPTZ,
    scheduled_at  TIMESTAMPTZ,
    template_id   UUID REFERENCES templates(id) ON DELETE SET NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT notifications_channel_check
        CHECK (channel IN ('sms', 'email', 'push')),
    CONSTRAINT notifications_priority_check
        CHECK (priority IN ('low', 'normal', 'high')),
    CONSTRAINT notifications_status_check
        CHECK (status IN ('pending', 'queued', 'processing', 'delivered', 'failed', 'retrying', 'cancelled'))
);

-- Indexes per CLAUDE.md §11.
-- The idempotency_key index is partial: only enforce uniqueness when a key
-- is actually supplied. Callers may omit it (empty string or NULL); without
-- the predicate every "" would collide.
CREATE UNIQUE INDEX idx_notifications_idempotency_key
    ON notifications (idempotency_key)
    WHERE idempotency_key IS NOT NULL AND idempotency_key <> '';

CREATE INDEX idx_notifications_status_scheduled_at
    ON notifications (status, scheduled_at);

CREATE INDEX idx_notifications_batch_id
    ON notifications (batch_id);

-- Reconciler scans for overdue retrying rows; partial index keeps it tight.
CREATE INDEX idx_notifications_retrying_next_retry_at
    ON notifications (next_retry_at)
    WHERE status = 'retrying';

CREATE INDEX idx_notifications_created_at_desc
    ON notifications (created_at DESC);

CREATE INDEX idx_notifications_correlation_id
    ON notifications (correlation_id);

CREATE TRIGGER set_updated_at_notifications
    BEFORE UPDATE ON notifications
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();

-- --- notification_logs ---------------------------------------------------
-- Append-only audit trail. One row per status transition, plus the initial
-- 'created' row written when the notification first lands. Powers the
-- trace endpoint (CLAUDE.md §12.3).

CREATE TABLE notification_logs (
    id              UUID PRIMARY KEY,
    notification_id UUID NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
    correlation_id  TEXT NOT NULL,
    event           TEXT NOT NULL,
    details         JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT notification_logs_event_check
        CHECK (event IN ('created', 'queued', 'processing', 'delivered', 'retrying', 'failed', 'cancelled'))
);

CREATE INDEX idx_notification_logs_notification_id_created_at
    ON notification_logs (notification_id, created_at);

CREATE INDEX idx_notification_logs_correlation_id
    ON notification_logs (correlation_id);

COMMIT;
