// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batches.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBatch = `-- name: CreateBatch :exec

INSERT INTO batches (id, correlation_id, created_at)
VALUES ($1, $2, $3)
`

type CreateBatchParams struct {
	ID            pgtype.UUID
	CorrelationID string
	CreatedAt     pgtype.Timestamptz
}

// batches.sql — query catalog for the batches table.
func (q *Queries) CreateBatch(ctx context.Context, arg CreateBatchParams) error {
	_, err := q.db.Exec(ctx, createBatch, arg.ID, arg.CorrelationID, arg.CreatedAt)
	return err
}

const getBatch = `-- name: GetBatch :one
SELECT id, correlation_id, created_at
FROM batches
WHERE id = $1
`

func (q *Queries) GetBatch(ctx context.Context, id pgtype.UUID) (Batch, error) {
	row := q.db.QueryRow(ctx, getBatch, id)
	var i Batch
	err := row.Scan(&i.ID, &i.CorrelationID, &i.CreatedAt)
	return i, err
}
