// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Batch struct {
	ID            pgtype.UUID
	CorrelationID string
	CreatedAt     pgtype.Timestamptz
}

type Notification struct {
	ID             pgtype.UUID
	BatchID        pgtype.UUID
	IdempotencyKey *string
	CorrelationID  string
	Channel        string
	Priority       string
	Recipient      string
	Content        string
	Status         string
	Attempts       int32
	LastError      string
	NextRetryAt    pgtype.Timestamptz
	ScheduledAt    pgtype.Timestamptz
	TemplateID     pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type NotificationLog struct {
	ID             pgtype.UUID
	NotificationID pgtype.UUID
	CorrelationID  string
	Event          string
	Details        []byte
	CreatedAt      pgtype.Timestamptz
}

type Template struct {
	ID        pgtype.UUID
	Name      string
	Channel   string
	Body      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
