// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimForProcessing = `-- name: ClaimForProcessing :one

UPDATE notifications
SET    status     = 'processing',
       updated_at = $2,
       attempts   = attempts + 1
WHERE  id = $1
  AND  status IN ('queued', 'retrying')
RETURNING id, batch_id, idempotency_key, correlation_id, channel, priority, recipient, content, status, attempts, last_error, next_retry_at, scheduled_at, template_id, created_at, updated_at
`

type ClaimForProcessingParams struct {
	ID        pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

// ClaimForProcessing atomically moves a notification from queued/retrying
// into processing and increments the attempts counter. Returning zero rows
// means another worker (or a redelivery) won the race; the repository
// surfaces this as ports.ErrAlreadyClaimed. See CLAUDE.md §3.10 / ADR-0009.
func (q *Queries) ClaimForProcessing(ctx context.Context, arg ClaimForProcessingParams) (Notification, error) {
	row := q.db.QueryRow(ctx, claimForProcessing, arg.ID, arg.UpdatedAt)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.IdempotencyKey,
		&i.CorrelationID,
		&i.Channel,
		&i.Priority,
		&i.Recipient,
		&i.Content,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.NextRetryAt,
		&i.ScheduledAt,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNotification = `-- name: CreateNotification :exec

INSERT INTO notifications (
    id, batch_id, idempotency_key, correlation_id,
    channel, priority, recipient, content,
    status, attempts, last_error,
    next_retry_at, scheduled_at, template_id,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11,
    $12, $13, $14,
    $15, $16
)
`

type CreateNotificationParams struct {
	ID             pgtype.UUID
	BatchID        pgtype.UUID
	IdempotencyKey *string
	CorrelationID  string
	Channel        string
	Priority       string
	Recipient      string
	Content        string
	Status         string
	Attempts       int32
	LastError      string
	NextRetryAt    pgtype.Timestamptz
	ScheduledAt    pgtype.Timestamptz
	TemplateID     pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

// notifications.sql — query catalog for the notifications table.
// Additional queries (ClaimForProcessing, List with cursor, reconciler
// scans) land in this file in later phase-3 tasks (PLAN.md tasks 7, 11, 13).
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.Exec(ctx, createNotification,
		arg.ID,
		arg.BatchID,
		arg.IdempotencyKey,
		arg.CorrelationID,
		arg.Channel,
		arg.Priority,
		arg.Recipient,
		arg.Content,
		arg.Status,
		arg.Attempts,
		arg.LastError,
		arg.NextRetryAt,
		arg.ScheduledAt,
		arg.TemplateID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const findOrphanedPending = `-- name: FindOrphanedPending :many

SELECT id, batch_id, idempotency_key, correlation_id, channel, priority, recipient, content, status, attempts, last_error, next_retry_at, scheduled_at, template_id, created_at, updated_at
FROM   notifications
WHERE  status      = 'pending'
  AND  created_at  < $1
ORDER BY created_at
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type FindOrphanedPendingParams struct {
	OlderThan pgtype.Timestamptz
	RowLimit  int32
}

// Reconciler queries (CLAUDE.md §3.11, ADR-0011). Each uses FOR UPDATE
// SKIP LOCKED so multiple reconciler instances can scan in parallel
// without conflicting claims — a row another reconciler has already
// locked is invisible to this query rather than blocking it.
func (q *Queries) FindOrphanedPending(ctx context.Context, arg FindOrphanedPendingParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, findOrphanedPending, arg.OlderThan, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.IdempotencyKey,
			&i.CorrelationID,
			&i.Channel,
			&i.Priority,
			&i.Recipient,
			&i.Content,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.NextRetryAt,
			&i.ScheduledAt,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOverdueRetrying = `-- name: FindOverdueRetrying :many
SELECT id, batch_id, idempotency_key, correlation_id, channel, priority, recipient, content, status, attempts, last_error, next_retry_at, scheduled_at, template_id, created_at, updated_at
FROM   notifications
WHERE  status         = 'retrying'
  AND  next_retry_at IS NOT NULL
  AND  next_retry_at  < $1
ORDER BY next_retry_at
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type FindOverdueRetryingParams struct {
	BeforeAt pgtype.Timestamptz
	RowLimit int32
}

func (q *Queries) FindOverdueRetrying(ctx context.Context, arg FindOverdueRetryingParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, findOverdueRetrying, arg.BeforeAt, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.IdempotencyKey,
			&i.CorrelationID,
			&i.Channel,
			&i.Priority,
			&i.Recipient,
			&i.Content,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.NextRetryAt,
			&i.ScheduledAt,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findStuckProcessing = `-- name: FindStuckProcessing :many
SELECT id, batch_id, idempotency_key, correlation_id, channel, priority, recipient, content, status, attempts, last_error, next_retry_at, scheduled_at, template_id, created_at, updated_at
FROM   notifications
WHERE  status      = 'processing'
  AND  updated_at  < $1
ORDER BY updated_at
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type FindStuckProcessingParams struct {
	OlderThan pgtype.Timestamptz
	RowLimit  int32
}

func (q *Queries) FindStuckProcessing(ctx context.Context, arg FindStuckProcessingParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, findStuckProcessing, arg.OlderThan, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.IdempotencyKey,
			&i.CorrelationID,
			&i.Channel,
			&i.Priority,
			&i.Recipient,
			&i.Content,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.NextRetryAt,
			&i.ScheduledAt,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotification = `-- name: GetNotification :one
SELECT id, batch_id, idempotency_key, correlation_id, channel, priority, recipient, content, status, attempts, last_error, next_retry_at, scheduled_at, template_id, created_at, updated_at
FROM notifications
WHERE id = $1
`

func (q *Queries) GetNotification(ctx context.Context, id pgtype.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.IdempotencyKey,
		&i.CorrelationID,
		&i.Channel,
		&i.Priority,
		&i.Recipient,
		&i.Content,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.NextRetryAt,
		&i.ScheduledAt,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many

SELECT id, batch_id, idempotency_key, correlation_id, channel, priority, recipient, content, status, attempts, last_error, next_retry_at, scheduled_at, template_id, created_at, updated_at
FROM   notifications
WHERE  ($1::text          IS NULL OR status   = $1)
  AND  ($2::text         IS NULL OR channel  = $2)
  AND  ($3::uuid        IS NULL OR batch_id = $3)
  AND  ($4::timestamptz  IS NULL OR created_at >= $4)
  AND  ($5::timestamptz IS NULL OR created_at <= $5)
  AND  ($6::timestamptz IS NULL
        OR (created_at, id) < ($6::timestamptz, $7::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $8
`

type ListNotificationsParams struct {
	Status          *string
	Channel         *string
	BatchID         pgtype.UUID
	CreatedAfter    pgtype.Timestamptz
	CreatedBefore   pgtype.Timestamptz
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	RowLimit        int32
}

// ListNotifications returns a page of notifications matching the supplied
// filters, ordered by (created_at DESC, id DESC). The keyset cursor (the
// last row's (created_at, id) tuple, base64-encoded by the repository) is
// compared as a Postgres composite so same-microsecond timestamps tiebreak
// on the id column. Every filter is nullable via sqlc.narg — pass NULL
// to skip the predicate. The repository fetches limit+1 rows so it can
// tell when more pages exist without an extra count query.
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.Status,
		arg.Channel,
		arg.BatchID,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.IdempotencyKey,
			&i.CorrelationID,
			&i.Channel,
			&i.Priority,
			&i.Recipient,
			&i.Content,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.NextRetryAt,
			&i.ScheduledAt,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :execrows

UPDATE notifications
SET    status        = $1,
       attempts      = $2,
       last_error    = $3,
       next_retry_at = $4,
       updated_at    = $5
WHERE  id              = $6
  AND  status          = $7
`

type UpdateNotificationStatusParams struct {
	NewStatus      string
	Attempts       int32
	LastError      string
	NextRetryAt    pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ID             pgtype.UUID
	ExpectedSource string
}

// UpdateNotificationStatus persists the mutations a use case applied to
// a notification entity (Cancel / MarkDelivered / MarkFailed / MarkRetrying).
// The WHERE clause includes the expected source status as a concurrency
// guard: zero rows affected means another writer changed the row between
// the read and this update. The repository surfaces this as
// ports.ErrConcurrentUpdate.
func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateNotificationStatus,
		arg.NewStatus,
		arg.Attempts,
		arg.LastError,
		arg.NextRetryAt,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedSource,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
