// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendNotificationLog = `-- name: AppendNotificationLog :exec

INSERT INTO notification_logs (
    id, notification_id, correlation_id, event, details, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type AppendNotificationLogParams struct {
	ID             pgtype.UUID
	NotificationID pgtype.UUID
	CorrelationID  string
	Event          string
	Details        []byte
	CreatedAt      pgtype.Timestamptz
}

// notification_logs.sql — query catalog for the notification_logs table.
func (q *Queries) AppendNotificationLog(ctx context.Context, arg AppendNotificationLogParams) error {
	_, err := q.db.Exec(ctx, appendNotificationLog,
		arg.ID,
		arg.NotificationID,
		arg.CorrelationID,
		arg.Event,
		arg.Details,
		arg.CreatedAt,
	)
	return err
}

const listNotificationLogs = `-- name: ListNotificationLogs :many
SELECT id, notification_id, correlation_id, event, details, created_at
FROM notification_logs
WHERE notification_id = $1
ORDER BY created_at
`

func (q *Queries) ListNotificationLogs(ctx context.Context, notificationID pgtype.UUID) ([]NotificationLog, error) {
	rows, err := q.db.Query(ctx, listNotificationLogs, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationLog{}
	for rows.Next() {
		var i NotificationLog
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.CorrelationID,
			&i.Event,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
