// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTemplate = `-- name: CreateTemplate :exec

INSERT INTO templates (id, name, channel, body, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateTemplateParams struct {
	ID        pgtype.UUID
	Name      string
	Channel   string
	Body      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// templates.sql — query catalog for the templates table.
func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) error {
	_, err := q.db.Exec(ctx, createTemplate,
		arg.ID,
		arg.Name,
		arg.Channel,
		arg.Body,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates
WHERE id = $1
`

func (q *Queries) DeleteTemplate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTemplate, id)
	return err
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, name, channel, body, created_at, updated_at
FROM templates
WHERE id = $1
`

func (q *Queries) GetTemplate(ctx context.Context, id pgtype.UUID) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Channel,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByName = `-- name: GetTemplateByName :one
SELECT id, name, channel, body, created_at, updated_at
FROM templates
WHERE name = $1
`

func (q *Queries) GetTemplateByName(ctx context.Context, name string) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByName, name)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Channel,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, name, channel, body, created_at, updated_at
FROM templates
ORDER BY name
LIMIT $1
`

func (q *Queries) ListTemplates(ctx context.Context, limit int32) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Channel,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :exec
UPDATE templates
SET name = $2,
    channel = $3,
    body = $4
WHERE id = $1
`

type UpdateTemplateParams struct {
	ID      pgtype.UUID
	Name    string
	Channel string
	Body    string
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) error {
	_, err := q.db.Exec(ctx, updateTemplate,
		arg.ID,
		arg.Name,
		arg.Channel,
		arg.Body,
	)
	return err
}
